const STEP_TYPES = {
      SET_NAME_INFO: 'SET_COUNT_PAGES',
      SET_ACTIVE_STEPS: 'SET_STEPS',
      SET_ACTIVE_STEPS_NEXT: 'SET_ACTIVE_STEPS_NEXT',
      SET_ACTIVE_STEPS_BACK: 'SET_ACTIVE_STEPS_BACK',
      SET_ACTIVE_STEPS_RESET: 'SET_ACTIVE_STEPS_RESET'
};

export default STEP_TYPES;
